"""create_credit_packages_table

Revision ID: 3fc3e9e41696
Revises: 0779b5ae86d2
Create Date: 2026-06-04 20:32:32.964323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc3e9e41696'
down_revision: Union[str, Sequence[str], None] = '0779b5ae86d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_credit_packages_active', 'credit_packages', ['is_active'], unique=False)
    op.create_index('idx_credit_packages_price', 'credit_packages', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_credit_packages_price', table_name='credit_packages')
    op.drop_index('idx_credit_packages_active', table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
