"""create workflows usages executions

Revision ID: ba90719a1e17
Revises: 3fc3e9e41696
Create Date: 2026-06-05 13:57:38.017473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba90719a1e17'
down_revision: Union[str, Sequence[str], None] = '3fc3e9e41696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('n8n_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('n8n_workflow_id')
    )
    op.create_index('idx_workflows_agent_active', 'workflows', ['agent_id', 'is_active'], unique=False)
    op.create_index('idx_workflows_agent_id', 'workflows', ['agent_id'], unique=False)
    op.create_index('idx_workflows_cost', 'workflows', ['execution_cost'], unique=False)
    op.create_index('idx_workflows_is_active', 'workflows', ['is_active'], unique=False)
    op.create_index('idx_workflows_n8n_workflow_id', 'workflows', ['n8n_workflow_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('n8n_execution_id', sa.String(length=255), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_consumed', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_response_status', sa.Integer(), nullable=True),
    sa.Column('webhook_response_body', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('n8n_execution_id')
    )
    op.create_index('idx_workflow_executions_agent_id', 'workflow_executions', ['agent_id'], unique=False)
    op.create_index('idx_workflow_executions_agent_status', 'workflow_executions', ['agent_id', 'status'], unique=False)
    op.create_index('idx_workflow_executions_created_at', 'workflow_executions', ['created_at'], unique=False)
    op.create_index('idx_workflow_executions_credits', 'workflow_executions', ['credits_consumed'], unique=False)
    op.create_index('idx_workflow_executions_n8n_execution_id', 'workflow_executions', ['n8n_execution_id'], unique=False)
    op.create_index('idx_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_executions_status_created', 'workflow_executions', ['status', 'created_at'], unique=False)
    op.create_index('idx_workflow_executions_workflow_id', 'workflow_executions', ['workflow_id'], unique=False)
    op.create_index('idx_workflow_executions_workflow_status', 'workflow_executions', ['workflow_id', 'status'], unique=False)
    op.create_table('usages',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('workflow_execution_id', sa.UUID(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usages_agent', 'usages', ['agent_id'], unique=False)
    op.create_index('idx_usages_agent_created', 'usages', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_usages_agent_type', 'usages', ['agent_id', 'usage_type'], unique=False)
    op.create_index('idx_usages_created_at', 'usages', ['created_at'], unique=False)
    op.create_index('idx_usages_type', 'usages', ['usage_type'], unique=False)
    op.create_index('idx_usages_wallet', 'usages', ['wallet_id'], unique=False)
    op.create_index('idx_usages_workflow_execution', 'usages', ['workflow_execution_id'], unique=False)
    op.create_index(op.f('ix_usages_agent_id'), 'usages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usages_wallet_id'), 'usages', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_usages_workflow_execution_id'), 'usages', ['workflow_execution_id'], unique=False)
    op.drop_index(op.f('idx_wallets_agent'), table_name='wallets')
    op.create_index('idx_wallets_agent_balance', 'wallets', ['agent_id', 'balance'], unique=False)
    op.create_index('idx_wallets_balance', 'wallets', ['balance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallets_balance', table_name='wallets')
    op.drop_index('idx_wallets_agent_balance', table_name='wallets')
    op.create_index(op.f('idx_wallets_agent'), 'wallets', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_usages_workflow_execution_id'), table_name='usages')
    op.drop_index(op.f('ix_usages_wallet_id'), table_name='usages')
    op.drop_index(op.f('ix_usages_agent_id'), table_name='usages')
    op.drop_index('idx_usages_workflow_execution', table_name='usages')
    op.drop_index('idx_usages_wallet', table_name='usages')
    op.drop_index('idx_usages_type', table_name='usages')
    op.drop_index('idx_usages_created_at', table_name='usages')
    op.drop_index('idx_usages_agent_type', table_name='usages')
    op.drop_index('idx_usages_agent_created', table_name='usages')
    op.drop_index('idx_usages_agent', table_name='usages')
    op.drop_table('usages')
    op.drop_index('idx_workflow_executions_workflow_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_workflow_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status_created', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_n8n_execution_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_credits', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_created_at', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_agent_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_agent_id', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_workflows_n8n_workflow_id', table_name='workflows')
    op.drop_index('idx_workflows_is_active', table_name='workflows')
    op.drop_index('idx_workflows_cost', table_name='workflows')
    op.drop_index('idx_workflows_agent_id', table_name='workflows')
    op.drop_index('idx_workflows_agent_active', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
